version: '3.9'

services:
  google-sheets:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: google-sheets-dev
    restart: always
    environment:
      - USERNAME=
      - PASSWORD=
      - SHEET_ID=
      - SEMESTER=
    volumes:
      - .:/app
